adop-java-slave:
  container_name: ${JAVA_SLAVE_NAME}
  restart: always
  image: janhout/adop-jenkins-slave:0.1.6
  net: ${DOCKER_NETWORK_NAME}
  privileged: true
  volumes:
    - ${JAVA_SLAVE_NAME}_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    SLAVE_NAME: ${JAVA_SLAVE_NAME}
    SLAVE_LABELS: ${JAVA_SLAVE_NAME}
    SWARM_PASSWORD: ${SWARM_PASSWORD}
    SLAVE_EXECUTORS: ${SLAVE_EXECUTORS}
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}